name = "ignium-motorsport"
compatibility_date = "2026-05-12"

[[d1_databases]]
binding = "DB"
database_name = "ignium_motorsport"
database_id = "fff2a18d-840a-45ca-b229-6e7b95cd99d1"

[vars]
GRIDREP_API_BASE_URL = ""
GRIDREP_TEAM_DRIVER_CUSTOMER_IDS = ""
